import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { CardProductGrids } from "@mms/webmobile-sc-components";
import { ModularCardProduct } from "../src/CardProduct.mock";
import { Responsive, WidthProvider }  from "react-grid-layout";
const ResponsiveGridLayout = WidthProvider(Responsive);

const Home: NextPage = () => {
  const layout = [
    { i: "a", x: 0, y: 0, w: 1, h: 1 },
    { i: "b", x: 1, y: 0, w: 1, h: 1 },
    { i: "c", x: 2, y: 0, w: 1, h: 1 },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Playing Cards with Product Cards in a Next.js App
        </a>
      </header>
      <main>
        <ResponsiveGridLayout className="layout" cols={{ lg: 6, md: 6, sm: 6, xs: 4, xxs: 2 }} rowHeight={800}>
          <div key="a">
            {" "}
            {ModularCardProduct(
              CardProductGrids.COLUMN,
              true,
              "Product 1",
              undefined,
              true,
              true,
              true,
              true,
              false,
              true,
              false,
              true,
              true
            )}
          </div>
          <div key="b">
            {ModularCardProduct(
              CardProductGrids.COLUMN,
              true,
              "Product 2",
              undefined,
              false,
              true,
              true,
              true,
              false,
              true,
              true,
              true,
              true
            )}
          </div>
          <div key="c">
            {ModularCardProduct(
              CardProductGrids.COLUMN,
              true,
              "Product 3",
              undefined,
              false,
              true,
              true,
              true,
              false,
              true,
              true,
              true,
              true
            )}
          </div>
        </ResponsiveGridLayout>
      </main>
    </div>
  );
};

export default Home;
